### ISSUE TITLE
從藥師端收集到的一些系統提問彙整

### ISSUE THREAD

**Issue by charlie0228** [PDIS/mask-static#17]
#### 寫在前面：因為不知道這種彙整在哪裡，但是我沒辦法一個一個 repo 去反饋 issue，畢竟我也不知道是那些 issue，所以發在這邊，希望 @audreyt，與其他熱心的工程師們可以收到我們的反饋。

Dear 各位辛苦的工程師們：

首先在這邊感謝各位，在極短的時間內創建出各種不同可供查詢的 **[口‍罩供‍需資‍訊平‍台](https://mask.pdis.nat.gov.tw/)**

發放至今兩天也收到不少藥師們的反饋，彙整之後，想回報給各位工程師，希望有了這些反饋，可以讓系統更完美，讓口罩發放更加順利。

1. 不同口‍罩供‍需資‍訊平‍台的口罩存量有差異：

    許多民眾拿著各種不同平台的查詢頁面來購買口罩，但是有些查詢網站因為更新時間區間可能比較長，或是有些查詢網站的資料與 [健保特約機構口罩剩餘數量明細清單](https://data.nhi.gov.tw/resource/mask/maskdata.csv) 不同，造成民眾來到藥局的時候口罩已經售罄，儘管藥師已經耐心解釋說確實口罩已售罄，還是會有極少數的民眾不買帳，破壞了原本查詢系統的美意。

    希望各位工程師能協助在畫面上加註，**口罩數量以藥局實際存量為主，網站查詢之數量僅供參考。**

**Comment by audreyt** [comment]
1. 感謝藥師朋友們的貢獻與回應，醒語部份調整為：

`口罩數量以藥局實際存量為主，線上查詢之數量僅供參考。`

**Comment by audreyt** [comment]
<a href="https://mask.pdis.nat.gov.tw/"><img width="750" alt="截圖 2020-02-08 上午1 35 30" src="https://user-images.githubusercontent.com/20723/74051632-4de66400-4a13-11ea-9572-c6b74e3b2383.png"></a>

**Comment by charlie0228** [comment]
感謝協助修改文宣，也希望其他工程師一併協助宣導，謝謝

**Comment by audreyt** [comment]
已經加到共筆上： https://g0v.hackmd.io/gGrOI4_aTsmpoMfLP1OU4A

也已更新我在 FB 的綜整回應：
https://www.facebook.com/shu.w.zhengwei/posts/770830443408228?comment_id=771039203387352&reply_comment_id=771046213386651
